package demo.spring.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.apache.cxf.bindings.xformat.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-03T14:46:47.878+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.spring.demo/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @Action(input = "http://service.spring.demo/HelloWorld/sayHiRequest", output = "http://service.spring.demo/HelloWorld/sayHiResponse")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.spring.demo/", className = "demo.spring.service.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.spring.demo/", className = "demo.spring.service.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
